### ISSUE TITLE
Separate the print content

### ISSUE THREAD

**Issue by tonychangcheng** [BennyFranco/ng-pdf-make#2]
For example, print1() contains table1. If print2() contains table 2, it would print table1 plus table2. 

As pdfmakeService is injected as a singleton, all the print functions would use the same docDefinition.

**Comment by war3k** [comment]
You can just clear docDefinition data after each print :) smth like : 
this.pdfmake.docDefinition.content.length = 0;

**Comment by BennyFranco** [comment]
Hi @tonychangcheng! if you are using the service only in one component and you need change the information, the solution of @war3k it's right, **tell me** if you need an internal method to clear data.

In another way, exist different levels about the instance of a provider, for this case, the right way to implement the service is inject in each component, to create different instance of the service. If you're creating a reusable component to create PDF, you must inject in that component, and use the component when you need it. If this is the case, you need to do something like this:

```typescript
import { Component, OnInit } from '@angular/core';
import {PdfmakeService} from 'ng-pdf-make';

@Component({
  selector: 'app-test2',
  templateUrl: './test2.component.html',
  styleUrls: ['./test2.component.css'],
  providers: [PdfmakeService]
})
export class Test2Component implements OnInit {
  // Inject pdfmake service
  constructor(private pdfmake: PdfmakeService) { }

...


import { Component, OnInit } from '@angular/core';
import {PdfmakeService} from 'ng-pdf-make';

@Component({
  selector: 'app-test1',
  templateUrl: './test1.component.html',
  styleUrls: ['./test1.component.css'],
  providers: [PdfmakeService]
})
export class Test1Component implements OnInit {
  // Inject pdfmake service
  constructor(private pdfmake: PdfmakeService) { }

...
```

in the last case, the providers are different and document generate don't merge.

Tell me more about your implementation to find the best way to implement the library @tonychangcheng  @war3k 

Greetings!!

**Comment by tonychangcheng** [comment]
I ended up creating my own service and using pdfmake.js directly.
