### ISSUE TITLE
makeDecorator error (build --prod)

### ISSUE THREAD

**Issue by JPMonteroG** [BennyFranco/ng-pdf-make#6]
hi everybody, i have an issue when a it try to deploy the app, everything works perfectly on local but when i run ng build --prod it's show me the next error "Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function", i did not made any updates and a few days ago i'm abled to deployed without problems

**Comment by BennyFranco** [comment]
This should be fixed in version **0.1.1**.
Note: Compatibility with angular4  is under development.
